#!/bin/sh

if [[ "$ACTION" != "ifup" || "$INTERFACE" != "wan" ]]
then
	exit
fi

ip2=`ifstatus wan | jsonfilter -e '@["ipv4-address"][0].address')`

. /lib/functions/network.sh; network_get_ipaddr ip wan

if [ $ip != $ip2 ]
then
	logger -t grey_ip "Reconnecting wan - grey IP detected: $ip"
	ifup wan
fi
